name: CI

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install libscrypt
        run: |
          sudo apt-get install libscrypt0
          sudo apt-get install libscrypt-dev
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - name: Lint JavaScript
        run: |
          sudo npm install -g jshint
          jshint --exclude-path public/scripts/.jshintignore public/scripts
      - name: Install D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - name: Build
        run: dub build
      - name: Style checks
        run: |
          dub fetch dscanner
          dub run dscanner -- -S source/
      - name: Unit Tests
        run: dub test
