name: CI

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install native deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libscrypt0 libscrypt-dev
      - name: Lint JavaScript
        run: |
          sudo npm install -g jshint
          jshint --exclude-path public/scripts/.jshintignore public/scripts
      - name: Install D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-2.096.1
      - name: Build
        run: dub build
      - name: Style checks
        run: |
          dub fetch dscanner
          dub run dscanner -- -S source/
      - name: Unit Tests
        run: dub test
