name: CI

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Install D
        uses: mihails-strasuns/setup-dlang@v0.3.1
        with:
          compiler: dmd-latest
      - name: Install MariaDB
        run: |
          sudo apt-get install software-properties-common
          sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
          sudo add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mariadb.melbourneitmirror.net/repo/10.4/ubuntu bionic main'
          sudo apt-get update
          sudo apt-get install mariadb-server
          sudo mysql -e 'create database if not exists pastemyst;'
          sudo mysql -e 'create user tester@localhost;'
          sudo mysql -e 'grant all privileges on pastemyst.* to tester@localhost;'
          sudo mysql -e 'flush privileges;'
      - name: Build
        run: dub build
      - name: Test
        run: dub test
        env:
          MYSQL_HOST: localhost
          MYSQL_USER: tester
          MYSQL_DB: pastemyst
